modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "militaryarmor"
version = "1.0.0"
displayName = "Military Armor"
description = '''Военная броня: три комплекта — камуфляжный, тяжёлый штурмовой и арктический.'''

[[dependencies.militaryarmor]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.militaryarmor]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
